### ISSUE TITLE
Consider disabling required field form submission polyfill?

### ISSUE THREAD

**Issue by derekprior** [rails/rails-ujs#13]
jquery-ujs has a [longstanding issue](https://github.com/rails/jquery-ujs/issues/319) on this polyfill. Because it offers no visual feedback, it makes apps look broken. Worse, it will only appear broken in browsers that developers are less likely to use (Safari and old IE).

With the move to a new gem for ujs in 5.1 (I believe), is there the chance to remove this polyfill? It seems like this would not be a breaking change as old apps would have to opt in to rails-ujs?

**Comment by rafaelfranca** [comment]
👍  for removing it. Do you want to open a PR?

**Comment by derekprior** [comment]
Will do!
