### ISSUE TITLE
Applying rails-ujs using webpackers

### ISSUE THREAD

**Issue by nkpgardose** [rails/rails-ujs#22]
What's the right way to use rails-ujs with [webpacker](https://github.com/rails/webpacker)? What I did are the following:

1. Add snippet of code under `shared.js`
  ```js  
  plugins: [
    new webpack.ProvidePlugin({
      $: 'jquery',
      jQuery: 'jquery'
    }),
    new webpack.ProvidePlugin({
      rails: 'rails-ujs'
    })
  ],
  ```
2. Add this snippet of code on `app/javascript/packs/application.js`
  ```js
// This file is automatically compiled by Webpack, along with any other files
// present in this directory. You're encouraged to place your actual application logic in
// a relevant structure within app/javascript and only use these pack files to reference
// that code so it'll be compiled.
//
// To reference this file, add <%= javascript_pack_tag 'application' %> to the appropriate
// layout file, like app/views/layouts/application.html.erb

console.log($.fn.jquery);
rails.start();
console.log('Hello World from Webpacker');

  ```

`bin/webpack-watcher` will build well however I am receiving this error on my browser.
`ReferenceError: Can't find variable: Rails`

**Comment by jan-auer** [comment]
Looks like **rails-ujs** requires the file's `this` to be the global `window` object, which it is not in modules. For now, there is a shim as explained in the [webpack docs](https://webpack.github.io/docs/shimming-modules.html):

```js
require('imports-loader?this=>global!rails-ujs');
```

I didn't try this with ProvidePlugin but it should work, too...

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
