### ISSUE TITLE
Using rails-ujs with Browserify

### ISSUE THREAD

**Issue by efedorenko** [rails/rails-ujs#8]
What's the best way to use rails-ujs with Browserify?

Rails-UJS [calls the wrapper function on `this`](https://github.com/rails/rails-ujs/blob/master/dist/rails-ujs.js#L703) and not directly on `window` object, so it can't be properly exported as a Browserify module — neither simple `require('rails-ujs')` or `window.Rails = require('rails-ujs')` works. That said I am not sure if I'm missing a good reason to use `this` in this context, so holding off on sending a PR.

**Comment by liudangyi** [comment]
```JavaScript
var rails = require('rails-ujs')
rails.start()
```

Or choose the functionalities you want and call `delegate` manually.

**Comment by efedorenko** [comment]
Excellent, thank you! Should "Usage" section of README be updated with this?

**Comment by liudangyi** [comment]
Of course. I'm going to write a migration guide and update the readme recently.
